version: '3'

services:
  php-service:
    image: php:8.1-apache
    ports:
      - "80:80"
    volumes:
      - ./php-service:/var/www/html/

  mysql-service:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"