version: '3'

services:
  php-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    restart: always
    depends_on:
      - mysql-service

  mysql-test-service:
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"