version: '3'

services:
  php-service:
    image: php:8.1-cli
    ports:
      - "80:8080"
    volumes:
      - ./php-service:/var/www/html
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    restart: always
    depends_on:
      - mysql-service
    command:
      - php index.php
